# Generated by Django 5.2.8 on 2025-11-19 21:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('approver_l1', 'Approver Level 1'), ('approver_l2', 'Approver Level 2'), ('finance', 'Finance')], default='staff', help_text='User role determines access permissions', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or division of the user', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the purchase request', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title describing the purchase', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of items/services to be purchased')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of the purchase request', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the purchase request', max_length=20)),
                ('proforma', models.FileField(blank=True, help_text='Proforma invoice document (PDF/Image)', null=True, upload_to='proformas/%Y/%m/')),
                ('proforma_metadata', models.JSONField(blank=True, default=dict, help_text='Extracted metadata from proforma invoice')),
                ('purchase_order', models.FileField(blank=True, help_text='Generated purchase order document', null=True, upload_to='purchase_orders/%Y/%m/')),
                ('po_metadata', models.JSONField(blank=True, default=dict, help_text='Purchase order metadata')),
                ('receipt', models.FileField(blank=True, help_text='Receipt/invoice document uploaded after purchase', null=True, upload_to='receipts/%Y/%m/')),
                ('receipt_validation', models.JSONField(blank=True, default=dict, help_text='Validation results comparing receipt with PO')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time of last update')),
                ('created_by', models.ForeignKey(help_text='User who created this request', on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Approval level: 1 for L1 approver, 2 for L2 approver')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of this approval level', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Comments or notes from the approver')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date and time when the approval was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when approval record was created')),
                ('approver', models.ForeignKey(blank=True, help_text='User who processed this approval (assigned when approved/rejected)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(help_text='The purchase request being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.purchaserequest')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'ordering': ['level', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='core_purcha_status_e0aa01_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_by', 'status'], name='core_purcha_created_b64725_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['purchase_request', 'level'], name='core_approv_purchas_5c99fd_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver', 'status'], name='core_approv_approve_c0bc05_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status', 'level'], name='core_approv_status_e57f50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('purchase_request', 'level')},
        ),
    ]
